version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build:
      context: kafka
      dockerfile: Dockerfile
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: $CF_HOST_IP
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

#  kafka:
#    image: spotify/kafka
#    ports:
#      - 2181:2181
#      - 9092:9092
#    environment:
#      ADVERTISED_HOST: 192.168.99.100
#      ADVERTISED_PORT: 9092
  spring_boot:
    build: .
    depends_on:
      - kafka